### ISSUE TITLE
Commit Configuration

### ISSUE THREAD

**Issue by gekkowrld** [DestinedCodes/commit-assistant#1]
The configutations should use `--local` flag instead of `--global` so that if a user accidentally enters the wrong details, they can restore the settings easily. And it should as the user if the user wants to add their details manually, if not then the script could read from the git configurations file.

If possible it can initialize and create a repo on user's github if not yet created.

**Comment by sshdopey** [comment]
Thanks for the feedback @gekkowrld thanks for creating this issue, I'd be glad to work on this and add this feature. 

Would you like to work on this? It could be assigned to you. If not I'll work on the task and submit a PR later today.

**Comment by sshdopey** [comment]
@gekkowrld I suspect tge issue for the bug should be [here](https://github.com/DestinedCodes/commit-assistant/blob/e067619127aaedfe070bcf72688688070e1217a0/commit). You can fix thqt and submit a PR.  Gettin the already existing git cinfiguration would be something ill add later or you could chose to if interested.

```shell
# Set git config for the current user
if ! git config --global user.name "<user.name>"; then
    echo "Error: unable to set git user name"
    exit 1
fi

if ! git config --global user.email "<user.email>"; then
    echo "Error: unable to set git user email"
    exit 1
fi
```

**Comment by gekkowrld** [comment]
I'll be working on it, maybe sometime today, You can assign it to me

**Comment by sshdopey** [comment]
Its been assigned to you.🚀
