### ISSUE TITLE
Use flags to make the program more flexible

### ISSUE THREAD

**Issue by gekkowrld** [DestinedCodes/commit-assistant#7]
Use of flags as opossed to having a monolith program run is better.
This can help further modify the code to do more with less code.
When implementing the flags include the short and long form as GNU/Linux does it for easier usage.
Easy to memorize flags and Instructions for use is highly appreciated.

**Comment by sshdopey** [comment]
I'll handle this isue

**Comment by gekkowrld** [comment]
@DestinedCodes  How is it going?
